Add conservative point queries for bvh
svenstaro/bvh pull request #108
Opened 2024-06-27 14:45 UTC by Azkellas

I recently implemented a distance point query with a bvh for my crate mesh_to_sdf by trait extending this crate (see https://github.com/Azkellas/mesh_to_sdf/pull/75). This PR is an attempt to upstream the changes and would solve https://github.com/svenstaro/bvh/issues/56.

This PR is different from https://github.com/svenstaro/bvh/pull/43 which only returns shapes with aabb containing the query point. On the contrary, this PR returns a conservative list of candidates, one of which for sure contains the shape that is closest to the query point. This is needed since we can't know for sure if the query point is in the aabb of its closest object.

To do so, we keep track of the best minimum/maximum distance found yet in the tree. For each node we compute the aabb min/max distance from the point (the minimum is 0 if the point is inside). Then we can prune or investigate the subtrees depending on the aabb's min/max compared to the current best min/max.

This means the search visits a subtree and not a single linear branch. It might be interesting to add an `approx` version following https://github.com/svenstaro/bvh/pull/43 implementation which would be faster and "close enough".

I couldn't implement the `nearest_candidate` method for `FlatBvh`.  Pre-order no-stack no-recursion tree traversal requires to store the parent index in the node afaik. I didn't want to change the memory layout without talking about it first. This PR is in draft state for this reason.

Testing is a bit rudimentary (and no benchmark) as I did most of it in my crate and haven't ported it yet.
Anyway for 100k triangles and 15k queries (in mesh's bounding box) it is 10x faster than brute forcing while being exact.

Waht remains to be done:
- [ ] Upstream tests and benches
- [ ] Implement `nearest_candidate` for `FlatBvh`
- [ ] Implement an `approx` version? At least test the performance gain.

Thank you for the work, this crate is very useful.

2024-07-04 17:10 UTC, svenstaro commented
Thanks a lot! I will take an in-depth look soon. How do you think this interacts with #98? I think I would like to merge #98 first and I'm almost done with it but I don't want to negate your work. Could you take a look at let me know what you think?

2024-07-05 11:55 UTC, Azkellas commented
I think the two PR are mostly orthogonal and merging #98 shouldn't affect this PR much.
Interestingly, they share some similarities in the tree traversal, but I think it's better to keep them separate as the `nearest_candidates` does not need ordering and thus gives more room for optimization. My point-bvh distance query also suffers from the fact that it needs to visit aabbs that don't contain the query point. 
This PR also doesn't provide an iterator since it uses the whole result to prune the vector (often removing ~75% of the candidates).

2024-07-05 15:57 UTC, svenstaro commented
In a related note: Would you like to help me maintain this library? It's not getting enough love and could do with some better maintenance.

2024-07-06 02:59 UTC, svenstaro commented
I merged and released #98 so this one now needs a rebase. :)

2024-07-07 18:05 UTC, Azkellas commented
I rebased without issue.
This is what the benches look like at the moment.

```
test bvh::bvh_impl::bench::bench_nearest_candidates_1200_triangles_bvh        ... bench:       1,674.28 ns/iter (+/- 82.26)
test bvh::bvh_impl::bench::bench_nearest_candidates_120k_triangles_bvh        ... bench:      15,676.73 ns/iter (+/- 838.18)
test bvh::bvh_impl::bench::bench_nearest_candidates_12k_triangles_bvh         ... bench:       4,685.55 ns/iter (+/- 165.48)
test bvh::bvh_impl::bench::bench_nearest_candidates_sponza_bvh                ... bench:      47,883.61 ns/iter (+/- 4,195.02)
test testbase::bench_nearest_candidates_120k_triangles_list                   ... bench:     664,322.50 ns/iter (+/- 39,013.88)
test testbase::bench_nearest_candidates_120k_triangles_list_aabb              ... bench:     519,004.38 ns/iter (+/- 63,937.19)
test testbase::bench_nearest_candidates_sponza_list                           ... bench:     611,325.62 ns/iter (+/- 33,850.31)
test testbase::bench_nearest_candidates_sponza_list_aabb                      ... bench:     282,300.00 ns/iter (+/- 41,833.67)
```

I'm not against becoming a co-maintainer, we can talk about it to see what needs to be done.

2024-07-09 14:28 UTC, Azkellas commented
I implemented the function for flat bvh as well. The performances are equivalent. I think the PR is ready for review now. Not perfect but functional.

> [ ] Upstream tests and benches
> [x] Implement nearest_candidate for FlatBvh
> [ ] Implement an approx version? At least test the performance gain.

Regarding the checklist in the first post, benches are here, tests are still a bit lackluster.
The approx version actually doesn't make sense since for a query point outside of the bvh bounding box it would return an empty list.

2024-07-25 08:44 UTC, Azkellas commented
Have you had a chance to take a look?

2024-07-27 03:20 UTC, svenstaro commented
Sorry, I didn't get to it yet. It's on the top of my list!

2025-01-07 07:25 UTC, svenstaro commented
@finnbear do you wanna give this a look and perhaps resolve the conflicts?

2025-01-07 08:10 UTC, Azkellas commented
Nice to see some activity on the project! I have now a faster implementation on my crate (though not public yet) that simplifies the algorithm by asking the user for more information.

This PR finds nearest candidates by only using aabbs (requiring no more information from the user), while my latest implementation add a trait to query the exact distance on relevant leaves. This allows for a way better pruning and, IIRC, makes the whole query up to 3x faster for triangles. 

I'll try to make/update a PR this week.

2025-01-07 08:24 UTC, finnbear commented
Hi :)

> I'll try to make/update a PR this week.

Does it still make sense to review & merge this PR as-is?

2025-01-07 08:29 UTC, Azkellas commented
The two versions could cohabit (nearest candidates could be useful is the cost of computing the exact distance is really high), otherwise the new version should substitute this one.
Though if the cost is high it probably means the new version would prune better too.

I think you can can wait for my update before you try to rebase this version. :)

2025-01-07 08:32 UTC, svenstaro commented
Oh, thanks for the update @Azkellas! We'll wait then. Sorry again for the long wait, life got busy. :(

2025-01-07 08:59 UTC, Azkellas commented
> Sorry again for the long wait, life got busy. :( 

No problem, I turned on my computed for the first time in three months last Wednesday, so we're quite synchronized at least. :) 

> So as I understand it, you will create a new PR? Shall we close this one then? 

I'll see if it's easier to rebase this one or upstream from scratch.

2025-01-12 19:05 UTC, Azkellas commented
I updated the code with the latest implementation.

Now instead of keeping a limit (min, max) on the distance to the best shape, we keep track of the actual distance to the current best shape (taking the first shape arbitrarily  if the bvh is not empty).

The two good news are:
- The implementation is much easier to read and maintain than before
- Performance is much much better, from 6x faster for the 1200 triangles benchmark to 50x faster for sponza (the more triangles, the faster), and 1000x faster than the most naive implementation.

The two bad news are:
- This adds the `PointDistance` trait requirement for Shape, needed to query the exact distance (squared) from the shape to the query point on candidate leaf nodes.
- The flat bvh is not optimized for distance queries as the function cannot choose which child to check first. The flat bvh is ~5-10x slower depending on the size of the bvh (still 100x faster than a naive implementation).

I think the branch is ready for review.

<details>
<summary>Incremental benchmarks</summary>

```
// naive implementation: go through each shape one by one with no BVH
test testbase::bench_nearest_candidates_120k_triangles_list                   ... bench:     681,288.75 ns/iter (+/- 55,478.50)
test testbase::bench_nearest_candidates_120k_triangles_list_aabb              ... bench:     534,145.00 ns/iter (+/- 98,617.50)
test testbase::bench_nearest_candidates_sponza_list                           ... bench:     619,938.12 ns/iter (+/- 39,642.44)
test testbase::bench_nearest_candidates_sponza_list_aabb                      ... bench:     295,907.50 ns/iter (+/- 39,118.38)
```
```
// old version with aabb min/max distances only
test bvh::bvh_impl::bench::bench_nearest_candidates_1200_triangles_bvh        ... bench:       1,744.73 ns/iter (+/- 80.47)
test bvh::bvh_impl::bench::bench_nearest_candidates_120k_triangles_bvh        ... bench:      15,921.70 ns/iter (+/- 1,739.16)
test bvh::bvh_impl::bench::bench_nearest_candidates_12k_triangles_bvh         ... bench:       4,841.70 ns/iter (+/- 399.85)
test bvh::bvh_impl::bench::bench_nearest_candidates_sponza_bvh                ... bench:      50,180.16 ns/iter (+/- 6,593.96)
```
```
// first version with exact distance query on candidate leaf nodes
test bvh::bvh_impl::bench::bench_nearest_from_1200_triangles_bvh              ... bench:       1,539.03 ns/iter (+/- 116.92)
test bvh::bvh_impl::bench::bench_nearest_from_120k_triangles_bvh              ... bench:      15,680.75 ns/iter (+/- 1,989.23)
test bvh::bvh_impl::bench::bench_nearest_from_12k_triangles_bvh               ... bench:       4,207.26 ns/iter (+/- 454.26)
test bvh::bvh_impl::bench::bench_nearest_from_sponza_bvh                      ... bench:       8,367.80 ns/iter (+/- 640.04)
```
```
// take first shape as first guess instead of T::max
test bvh::bvh_impl::bench::bench_nearest_from_1200_triangles_bvh              ... bench:       1,101.38 ns/iter (+/- 89.26)
test bvh::bvh_impl::bench::bench_nearest_from_120k_triangles_bvh              ... bench:      11,637.48 ns/iter (+/- 1,637.42)
test bvh::bvh_impl::bench::bench_nearest_from_12k_triangles_bvh               ... bench:       3,053.51 ns/iter (+/- 407.65)
test bvh::bvh_impl::bench::bench_nearest_from_sponza_bvh                      ... bench:       5,031.79 ns/iter (+/- 456.78)
```
```
// go to best min child, useful to get a better first estimation of the best child.
test bvh::bvh_impl::bench::bench_nearest_from_1200_triangles_bvh              ... bench:         276.45 ns/iter (+/- 17.75)
test bvh::bvh_impl::bench::bench_nearest_from_120k_triangles_bvh              ... bench:         776.33 ns/iter (+/- 112.84)
test bvh::bvh_impl::bench::bench_nearest_from_12k_triangles_bvh               ... bench:         426.19 ns/iter (+/- 20.88)
test bvh::bvh_impl::bench::bench_nearest_from_sponza_bvh                      ... bench:       1,211.11 ns/iter (+/- 64.11)
```

```
// comparison with flat bvh
test bvh::bvh_impl::bench::bench_nearest_from_1200_triangles_bvh              ... bench:         284.03 ns/iter (+/- 21.04)
test bvh::bvh_impl::bench::bench_nearest_from_120k_triangles_bvh              ... bench:         837.90 ns/iter (+/- 264.71)
test bvh::bvh_impl::bench::bench_nearest_from_12k_triangles_bvh               ... bench:         427.79 ns/iter (+/- 23.38)
test flat_bvh::bench::bench_nearest_from_1200_triangles_bvh                   ... bench:         700.26 ns/iter (+/- 34.75)
test flat_bvh::bench::bench_nearest_from_120k_triangles_bvh                   ... bench:       8,509.34 ns/iter (+/- 1,119.36)
test flat_bvh::bench::bench_nearest_from_12k_triangles_bvh                    ... bench:       2,148.05 ns/iter (+/- 179.71)
```
</details>

2025-01-12 19:45 UTC, finnbear commented on src/aabb/aabb_impl.rs
> +    pub fn get_min_distance_2(&self, point: Point<T, D>) -> T {
Is there a reason why we use `_2` here and `_squared` elsewhere? Perhaps they should be consistent. I personally prefer `_squared`.

2025-01-12 19:52 UTC, finnbear commented on src/bounding_hierarchy.rs
> +    ) -> Option<(&'a Shape, T)>;
IMO it's worth calling this in the fuzzer (`fuzz/`) for a normal BVH and a flat BVH, even if the output is disregarded, to make sure it doesn't panic. A simple and easy check would be to make sure it returns `None` if and only if the BVH is empty at that moment.

If you are unsure about this, I'm happy to implement it myself in a followup PR.

2025-01-12 21:47 UTC, svenstaro commented on src/aabb/aabb_impl.rs
> +    pub fn get_min_distance_2(&self, point: Point<T, D>) -> T {
I agree with this. Let's keep it consistent. :)

2025-01-12 22:32 UTC, Azkellas commented on src/aabb/aabb_impl.rs
> +    pub fn get_min_distance_2(&self, point: Point<T, D>) -> T {
Indeed, refactorization miss here

2025-01-12 22:43 UTC, svenstaro reviewed
This is very cool! @finnbear do you have time to give this a proper review? Maybe even @dashedman if you feel like it. :) I probably won't have time.

2025-01-12 22:43 UTC, svenstaro commented on fuzz/fuzz_targets/fuzz.rs
> +    // Assume the shape is the point a.
What's point a?

2025-01-12 22:46 UTC, Azkellas commented on fuzz/fuzz_targets/fuzz.rs
> +    // Assume the shape is the point a.
It's not the case anymore, my bad, it's the center of the aabb now. Point a is one of the point that make the aabb, but before sanitization so I couldn't use it.

2025-01-12 23:03 UTC, finnbear commented
>  @finnbear do you have time to give this a proper review?

Yes! I mean, I can't start for ~3 hours, but definitely within the next couple days :)

2025-01-13 02:20 UTC, finnbear requested changes
Thanks for these changes! :rocket:

I've left some feedback that I hope you can address (if not, that's fine; I will personally drive the PR to completion rather than letting it become too stale).

As a final note, to the extent you feel comfortable doing so, please `git rebase` your revisions into meaningful commits. You can err on the side of squashing commits, especially those that "fix" prior commits. You may find the `git absorb` tool useful.

2025-01-13 02:20 UTC, finnbear commented on src/bvh/bvh_impl.rs
> +    ///
Wording feels slightly awkward, recommend: "Returns the closest shape to..."

2025-01-13 02:20 UTC, finnbear commented on src/bvh/bvh_impl.rs
> +        if shapes.is_empty() {
To be safe, considering the caller can manipulate `shapes`, let's use `self.nodes.is_empty()` instead.

2025-01-13 02:20 UTC, finnbear commented on src/bvh/bvh_impl.rs
> +        let mut best_candidate = (&shapes[0], shapes[0].distance_squared(origin));
Furthermore, `shapes[0]` is not *technically* guaranteed to be in the BVH. The user may have removed it without actually swapping/clearing it from the slice. I recommend passing down an `&mut Option<&Shape, T>` or something similar which can later be `unwrap`'d.

2025-01-13 02:20 UTC, finnbear commented on src/bvh/bvh_node.rs
> +    pub fn nearest_from_recursive<'a, Shape: Bounded<T, D> + PointDistance<T, D>>(
I realize that other similar functions may still be public, but AFAIK we're moving away from doing that. Let's make this new one private or `pub(crate)`, as needed.

2025-01-13 02:20 UTC, finnbear commented on src/bvh/bvh_node.rs
> +        origin: nalgebra::Point<T, D>,
IMO `query` might be clearer than `origin`

2025-01-13 02:20 UTC, finnbear commented on src/flat_bvh.rs
> +        let mut best_element = (&shapes[0], shapes[0].distance_squared(query));
`shapes[0]` may suffer from the same issue as in the normal BVH (see previous comment)

2025-01-13 02:20 UTC, finnbear commented on src/testbase.rs
> +        let _best_result = bh.nearest_from(point, triangles);
This benchmark could be optimized away unless you pass the output to `std::hint::black_box`.

Also applies to:
- `nearest_from_list`
- `nearest_from_list_aabb`

2025-01-14 22:16 UTC, Azkellas commented on fuzz/fuzz_targets/fuzz.rs
> +        offset.dot(&offset)
It's two different things.
The `Aabb::min_distance_squared` is used to prune for cheap in the tree traversal with a low estimation of the actual distance, while `PointDistance` is the (potentially expensive) actual distance on leaf nodes.

Here I decided in the fuzzer the objects were points, in the center of the cell. I could have decided the objects were the aabb themselves, but I prefered having two different objects to consider. Ideally the object should be a random point/shape in the aabb.

2025-01-14 22:17 UTC, Azkellas commented on fuzz/fuzz_targets/fuzz.rs
> +        Debug::fmt(&(&self.aabb(), &self.a), f)
There was when the actual object was `a` and not the center of the aabb, but that didn't work as `a` was often outside `self.aabb()` due to how it's generated.

2025-01-14 22:24 UTC, Azkellas commented on fuzz/fuzz_targets/fuzz.rs
> +        assert_agreement: bool,
Yeah tbh I used the assert agreement to match the traversal signature without looking at how it was called. Indeed it doesn't really makes sense in that case I think.

I think we should remove the boolean but keep all current asserts, even if they're not perfect (e.g. `float_cmp::approx_eq`) they are still a safeguard if things go really wrong.

2025-01-14 22:31 UTC, Azkellas commented on src/bvh/bvh_impl.rs
> +        let mut best_candidate = (&shapes[0], shapes[0].distance_squared(origin));
would it makes sense to use `self.nodes[0]` instead of `shapes[0]` or even that is not guaranteed?

2025-01-14 22:34 UTC, finnbear commented on src/bvh/bvh_impl.rs
> +        let mut best_candidate = (&shapes[0], shapes[0].distance_squared(origin));
Sure, you would then have to handle both cases (`self.nodes[0]` is an internal node **or** a leaf node)

2025-01-14 23:07 UTC, Azkellas commented on src/testbase.rs
> +        let _best_result = bh.nearest_from(point, triangles);
Not sure where you want to put them for the list/aabb versions, unless you want to wrap the call to the functions themselves.

2025-01-14 23:10 UTC, Azkellas commented
I adressed the review and rebased to latest main commit. A couple points are still open.
Regarding the main comment and squashing, I tend to squash as I go in PRs, so I didn't change the number/name of the commit during this review, tell me if you want less commits.

2025-01-14 23:26 UTC, finnbear commented on src/testbase.rs
> +        let _best_result = bh.nearest_from(point, triangles);
You could pass `min_dist` to `black_box` at the end :)

2025-01-14 23:33 UTC, svenstaro commented
I prefer not squashing so long as the commits in a PR tell a story and are properly rebased. [git-absorb](https://github.com/tummychow/git-absorb) is quite helpful here.

2025-01-15 05:36 UTC, dashedman commented on src/flat_bvh.rs
> +                let shape = &shapes[node.shape_index as usize];
Maybe we should move this rule to function `fn is_leaf(&self) -> bool` ?

2025-01-15 05:44 UTC, finnbear commented on src/flat_bvh.rs
> +                let shape = &shapes[node.shape_index as usize];
Good idea!

2025-01-15 06:11 UTC, dashedman commented
So, what are you doing here?
 New feature just returns nearest shape to the any passed point?

2025-01-15 06:32 UTC, dashedman commented on src/bvh/bvh_impl.rs
> +        self.nearest_from(query, shapes)
I don't understand. It's just an infinite recursive or what?

2025-01-15 06:33 UTC, dashedman commented on src/bvh/bvh_node.rs
> +        best_candidate: &mut Option<(&'a Shape, T)>,
It's just my tastes, but I'm prefer to return new value from func instead of using in-out args

2025-01-15 07:09 UTC, finnbear commented on src/bvh/bvh_impl.rs
> +        self.nearest_from(query, shapes)
This is within
```
impl<T: BHValue + std::fmt::Display, const D: usize> BoundingHierarchy<T, D> for Bvh<T, D> {
```

A trait function is being implemented by calling an inherent function of the same name.

2025-01-15 08:13 UTC, dashedman commented on src/bvh/bvh_impl.rs
> +        self.nearest_from(query, shapes)
Why are we not write implementation just in trait imply for this structure?

2025-01-15 08:21 UTC, finnbear commented on src/bvh/bvh_impl.rs
> +        self.nearest_from(query, shapes)
I would assume:
1.  consistency. prior code uses both inherent and trait functions
2. usability. using a trait function requires importing the trait; using an inherent function doesn't

2025-01-15 08:22 UTC, dashedman commented on src/bvh/bvh_impl.rs
> +        self.nearest_from(query, shapes)
Ok

2025-01-15 16:37 UTC, svenstaro requested changes

2025-01-15 16:37 UTC, svenstaro commented on src/bvh/bvh_node.rs
> +        best_candidate: &mut Option<(&'a Shape, T)>,
I agree with this. The rest of the library also uses return values.

2025-01-15 17:23 UTC, Azkellas commented on src/bvh/bvh_impl.rs
> +        self.nearest_from(query, shapes)
It was done for consistency with the traverse methods.

2025-01-15 17:56 UTC, Azkellas commented on src/bvh/bvh_node.rs
> +        best_candidate: &mut Option<(&'a Shape, T)>,
While it's possible to use return values to update best_candidate, I'm not sure it makes the code much cleaner. Worse, the performances drop.
I checked both versions traverse the tree the same way to make sure it's not a logic issue, so I guess it's a compiler optimization. I haven't investigated more.

with `&mut`
```
test bvh::bvh_impl::bench::bench_nearest_from_1200_triangles_bvh              ... bench:         284.00 ns/iter (+/- 20.23)
test bvh::bvh_impl::bench::bench_nearest_from_120k_triangles_bvh              ... bench:         812.96 ns/iter (+/- 169.83)
test bvh::bvh_impl::bench::bench_nearest_from_12k_triangles_bvh               ... bench:         427.06 ns/iter (+/- 23.12)
test bvh::bvh_impl::bench::bench_nearest_from_sponza_bvh                      ... bench:       1,216.93 ns/iter (+/- 92.07)
```

when returning best candidate

```
test bvh::bvh_impl::bench::bench_nearest_from_1200_triangles_bvh              ... bench:         396.98 ns/iter (+/- 16.86)
test bvh::bvh_impl::bench::bench_nearest_from_120k_triangles_bvh              ... bench:       1,033.95 ns/iter (+/- 402.01)
test bvh::bvh_impl::bench::bench_nearest_from_12k_triangles_bvh               ... bench:         577.19 ns/iter (+/- 44.53)
test bvh::bvh_impl::bench::bench_nearest_from_sponza_bvh                      ... bench:       1,474.12 ns/iter (+/- 170.15)
```

<details>
<summary>Code to test with return value</summary>

```rust

    pub(crate) fn nearest_from_recursive<'a, Shape: Bounded<T, D> + PointDistance<T, D>>(
        nodes: &[BvhNode<T, D>],
        node_index: usize,
        query: nalgebra::Point<T, D>,
        shapes: &'a [Shape],
        mut best_candidate: Option<(&'a Shape, T)>,
    ) -> Option<(&'a Shape, T)> {
        match nodes[node_index] {
            BvhNode::Node {
                ref child_l_aabb,
                child_l_index,
                ref child_r_aabb,
                child_r_index,
                ..
            } => {
                // Compute the min dist for both children
                let mut children = [
                    (child_l_index, child_l_aabb.min_distance_squared(query)),
                    (child_r_index, child_r_aabb.min_distance_squared(query)),
                ];

                // Sort children to go to the best candidate first and have a better chance of pruning
                if children[0].1 > children[1].1 {
                    children.swap(0, 1);
                }

                // Traverse children
                for (index, child_dist) in children {
                    // Node might contain a better shape: check it.
                    if best_candidate.is_none_or(|(_, best_dist)| child_dist <= best_dist) {
                        best_candidate = Self::nearest_from_recursive(
                            nodes,
                            index,
                            query,
                            shapes,
                            best_candidate,
                        );
                    }
                }
            }
            BvhNode::Leaf { shape_index, .. } => {
                // This leaf might contain a better shape: check it directly with its exact distance (squared).
                let dist = shapes[shape_index].distance_squared(query);

                if best_candidate.is_none_or(|(_, best_dist)| dist < best_dist) {
                    best_candidate = Some((&shapes[shape_index], dist));
                }
            }
        }

        best_candidate
    }

````
</details>

2025-01-15 19:00 UTC, svenstaro commented on src/bvh/bvh_node.rs
> +        best_candidate: &mut Option<(&'a Shape, T)>,
Alright, then let's keep your original version.

2025-01-15 19:47 UTC, dashedman commented on src/bvh/bvh_node.rs
> +        best_candidate: &mut Option<(&'a Shape, T)>,
Try please this version for me 

```rust
pub(crate) fn nearest_from_recursive<'a, Shape: Bounded<T, D> + PointDistance<T, D>>(
        nodes: &[BvhNode<T, D>],
        node_index: usize,
        query: nalgebra::Point<T, D>,
        shapes: &'a [Shape],
        best_candidate: Option<(&'a Shape, T)>,
    ) -> Option<(&'a Shape, T)> {
        match nodes[node_index] {
            BvhNode::Node {
                ref child_l_aabb,
                child_l_index,
                ref child_r_aabb,
                child_r_index,
                ..
            } => {
                // Compute the min dist for both children
                let mut children = [
                    (child_l_index, child_l_aabb.min_distance_squared(query)),
                    (child_r_index, child_r_aabb.min_distance_squared(query)),
                ];

                // Sort children to go to the best candidate first and have a better chance of pruning
                if children[0].1 > children[1].1 {
                    children.swap(0, 1);
                }

                // Traverse children
                for (index, child_dist) in children {
                    // Node might contain a better shape: check it.
                    if best_candidate.is_none_or(|(_, best_dist)| child_dist <= best_dist) {
                        return Self::nearest_from_recursive(
                            nodes,
                            index,
                            query,
                            shapes,
                            best_candidate,
                        )
                    }
                };
                best_candidate
            }
            BvhNode::Leaf { shape_index, .. } => {
                // This leaf might contain a better shape: check it directly with its exact distance (squared).
                let dist = shapes[shape_index].distance_squared(query);

                if best_candidate.is_none_or(|(_, best_dist)| dist < best_dist) {
                    Some((&shapes[shape_index], dist))
                }
            }
        }
    }
```

2025-01-15 22:08 UTC, Azkellas commented
Cargo fuzz does not build with latest nightly but that's not on me. Otherwise I think I dealt with all the reviews, I let you double check and close them to be sure I didn't miss any.

2025-01-15 22:32 UTC, finnbear commented
> Cargo fuzz does not build with latest nightly but that's not on me.

Sorry about that! I just merged #143 which fixes the CI to a known-good version of nightly. If you rebase on to `master`, you should get the benefit of that.

2025-01-15 22:33 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +    /// unexpected way.
This comment should no longer reference `assert_agreement`

2025-01-15 22:47 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +            .map(|(s, d)| (ByPtr(s), d));
I think the `ByPtr` wrapper isn't necessary here (or later in this function) because, as you say, you don't want to compare the shapes.

2025-01-15 22:49 UTC, finnbear commented on fuzz/Cargo.toml
> +float-cmp = "0.10.0"
`bvh` itself uses https://github.com/svenstaro/bvh/blob/ca417859cd3f33b129cd82079d1a90d7da543e0a/Cargo.toml#L18

```
abs_diff_eq!(1.0, 1.0);
abs_diff_eq!(1.0, 1.0, epsilon = f64::EPSILON);
```

Maybe the fuzzer should too, to avoid dependency proliferation.

2025-01-15 22:50 UTC, finnbear commented on src/flat_bvh.rs
> +    }
I'd prefer `pub fn`, as long as the rest of the `FlatNode` internals are public.

2025-01-15 22:54 UTC, finnbear requested changes
Looking good to me :+1:

I had a few more comments (see above).

Also, a slightly more subjective concern: would the name `nearest_to` be better than `nearest_from`? Even your documentation uses "to" in "Returns the shape closest **to** the query point".

2025-01-15 23:01 UTC, finnbear commented on src/bounding_hierarchy.rs
> +    /// Returns the shape closest to the query point.
A subjective concern: would the name `nearest_to` be better than `nearest_from`? Your documentation uses "to" here ;)

2025-01-17 18:54 UTC, Azkellas commented
Updated.

It has to be noted that the CI still fails because I used [Option::is_none_or](https://doc.rust-lang.org/std/option/enum.Option.html#method.is_none_or) that was introduced in 1.82.0. I don't know if bvh has a MSRV policy nor how it should evolved with the new cargo resolver. Let me know if that's an issue.

2025-01-17 19:39 UTC, finnbear commented
Thanks! I'm not aware of an MSRV policy but, out of self interest (I use a nightly compiler from almost a year ago, and upgrade it annually, based on how long it takes to find a specific nightly that compiles all my projects), it would be nice for the crate to work on Rust versions older than ~3 months.

Removing `is_none_or` may, however, require silencing a `clippy` lint, which is also undesirable.

I did a quick survey of MSRV's of other crates:
- `tokio`: currently >1 year old, but only guaranteed to be >=6 months old
- `regex`: currently 2-3 years old
- `glam`: currently >1 year old
- `nalgebra`: not explicitly listed

1y seems like a common denominator to aim for.

I suggest removing it, silencing the `clippy` lint that probably results from that, but adding a clear `TODO` comment to switch to `is_none_or` after Oct 17, 2025 (when `is_none_or` will have been stable for a year).

2025-01-18 11:25 UTC, Azkellas commented
Funnily enough the clippy lint doesn't work when dereferencing a reference to an option, but I had to use `#[allow(...)]` instead of `#[expect(...)]` since `expect` is too recent as well. The CI doesn't complain anymore.

2025-01-18 16:40 UTC, finnbear approved these changes
Nice work!

2025-01-19 18:12 UTC, merged