Add fuzzer, don't panic on empty bvh.
svenstaro/bvh pull request #113
Opened 2024-12-29 22:07 UTC by finnbear

I use this excellent library in 3 projects and wanted to ensure it won't panic :)

## Changes
- [x] Add fuzzer
  - [x] Build a BVH
  - [x] Assert consistent
  - [x] Assert tight.
  - [x] Flatten the BVH
  - [x] Traverse the BVH
    - [x] Normal
    - [x] Iterator
    - [x] Nearest
    - [x] Farthest
    - [x] Flat
    - [ ] ~~Assert all traversals output the same set of shapes~~ doesn't work, possibly due to rounding errors
    - [x] Assert nearest and farthest traversals output the same set of shapes
  - [x] Mutate a BVH
    - [x] Add shape(s)
    - [ ] ~~Remove shape(s)~~ causes internal panics
- [x] Run fuzzer in CI, for 5 minutes
- [x] Don't panic on empty BVH
  - [x] `assert_consistent` returns successfuly on an empty BVH
  - [x] `assert_tight` returns successfully on an empty BVH
  - [x] `is_consistent` returns `true` on an empty BVH
  - [x] `flatten` returns an empty flat BVH on an empty BVH
  - [ ] ~~Nearest/farthest iterators work on empty BVH~~ (merge #112 instead)

## Future work
- Fix internal panic in `remove_shape`.

2025-01-06 05:44 UTC, svenstaro commented
Very cool! Before giving this a more in-depth review: We're already using proptest which has a somewhat related goal (trying a bunch of constrained values). I feel we should perhaps only have one of these.

Also, I really like that you fixed the empty BVH case. However, I think that should be a separate PR (and a bunch of tests to show that it's fixed).

What do you think?

2025-01-06 05:54 UTC, finnbear commented
> We're already using proptest which has a somewhat related goal (trying a bunch of constrained values). I feel we should perhaps only have one of these.

There is some overlap here, but fuzzing has a distinct advantage because it recombines inputs to maximize code coverage, which can find edge-cases more efficiently than trying random inputs. IMO it's fine to have both, with `proptest` being used for writing manual tests of specific properties and fuzzing being used to automatically find gaps in those manual tests. Once the fuzzer finds something (like empty BVH panics), it should graduate to a normal unit test or `proptest`.


> Also, I really like that you fixed the empty BVH case. However, I think that should be a separate PR (and a bunch of tests to show that it's fixed).

Sure, I can move that change to another PR. It will make the fuzzer fail until the fixes are merged into `main` and this PR.

2025-01-06 08:48 UTC, svenstaro commented
Thanks! I merged all the things. Feel free to rebase.

2025-01-06 11:32 UTC, svenstaro requested changes

2025-01-06 17:31 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +            // assert_eq!(traverse, traverse_iterator);
After this PR is merged, I will look into these. However, I don't think a fix is likely to exist, because each iterator/traversal uses slightly different ray-aabb intersections which will have different rounding errors for rays that just barely hit/miss a leaf AABB or node AABB.

I think a similar test could succeed on a modified BVH in which all AABB's are in a 3D grid, with their centers on integer coordinates, if each ray starts on an integer coordinate and travels in the X, Y, or Z direction.

2025-01-06 18:04 UTC, finnbear commented on fuzz/Cargo.toml
> +[package.metadata]
Done documenting. Can consider `Justfile` in separate PR.

2025-01-06 18:04 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +use nalgebra::{Point, SimdPartialOrd};
Good idea; done!

2025-01-06 18:45 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +            // assert_eq!(traverse, traverse_iterator);
Update: I just added that "similar test" and it actually makes this line pass. However, all other commented-out traversals can still disagree, which strongly implies the existence of bug(s).

2025-01-07 01:24 UTC, svenstaro commented on fuzz/Cargo.toml
> +[package.metadata]
That works for me!

2025-01-07 03:14 UTC, svenstaro requested changes
I finished the review. I think this is very cool and I've never used structural fuzzing this way as I'm usually content with just proptesting. I do see the point in this case, however.

I'm fine with the implementation but noted some parts where I'd like _even more_ comments. ;)

2025-01-07 03:14 UTC, svenstaro commented on fuzz/fuzz_targets/fuzz.rs
> +    fn fuzz(mut self) {
Perhaps make the reader aware to look at the module level documentation to get the gist of what we're trying to do in this function.

2025-01-07 03:14 UTC, svenstaro commented on fuzz/fuzz_targets/fuzz.rs
> +                self.ray.mode.is_grid() && self.shapes.iter().all(|s| s.mode.is_grid());
What's the idea behind this?

2025-01-07 03:14 UTC, svenstaro commented on fuzz/fuzz_targets/fuzz.rs
> +                // Fails, probably due to rounding errors.
Let's add TODOs for the failures. Perhaps even add an additional tracking issue to look into these?

2025-01-07 03:14 UTC, svenstaro commented on fuzz/fuzz_targets/fuzz.rs
> +                // Fails, probably due to rounding errors.
Like above, some TODOs to track these failures would be great.

2025-01-07 03:14 UTC, svenstaro commented on fuzz/fuzz_targets/fuzz.rs
> +}
This feels a bit like a crutch and it seems there should be a better way for us to compare these but I don't really have a better idea here either.

2025-01-07 03:29 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +            .normalize();
`normalize` here is an `nalgebra` function with a very standard implementation of (approximately) `self / sqrt(self.x^2 + self.y^2 + ...)`. Precision issues are to be expected when used with extremely large inputs that `Arbitrary` is happy to produce. The first normalize produces error depending on the input size. The second normalize has almost no error.

2025-01-07 03:34 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +        );
First of all, this fuzzing code could be written better as much of it is redundant. I will do that now.

Passing a vector with NaN, Infinity, or -Infinity components (what this was *supposed* to test for) is invalid input. If you want to protect users, we could make `Ray::new` panic if the direction has non-finite components.

2025-01-07 04:28 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +            .normalize();
This code actually normalized 3 times, 2 before `Ray::new` and 1 in `Ray::new`. In the current state of the code, we don't need to pre-normalize at all; the `Ray::new` normalization is sufficient. I think I wrote this kludge before limiting the arbitrary coordinate magnitudes to something reasonable.

2025-01-07 04:29 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +        );
This code became unnecessary after I started limiting coordinates. I replaced it with a simple check for zero vectors (if both input points are the same).

2025-01-07 04:34 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +                self.ray.mode.is_grid() && self.shapes.iter().all(|s| s.mode.is_grid());
Commented!

2025-01-07 04:34 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +                // Fails, probably due to rounding errors.
Done and done

2025-01-07 04:36 UTC, finnbear commented on fuzz/fuzz_targets/fuzz.rs
> +}
This was the best thing I could think of. If this was a normal unit test, I'd give each shape a unique numerical ID and compare sets of ID's. However, an *arbitrary* shape cannot really be made to have a unique ID, so we use the pointer instead.

This method leads to good debug output when things go wrong since the shapes are actually printed.

2025-01-07 04:58 UTC, svenstaro commented on fuzz/fuzz_targets/fuzz.rs
> +        );
Excellent :+1:

2025-01-07 05:07 UTC, merged